name = "smart_meter_gateway_sample_data_generator"
version = "1.0.0"

description = "A generator to provide SMG data for protoyping"
licences = ["AGPL-3.0"]
repository = { type = "github", user = "SturmDerLiebe", repo = "smart_meter_gateway_sample_data_generator" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.0 and < 2.0.0"
